### ISSUE TITLE
[BUG] driving backwards with forward direction set

### ISSUE THREAD

**Issue by Snickers125** [stijnwop/shuttledrivedirection#1]
**Describe the bug**
Vehicle driving backwards with forward direction set 

**To Reproduce**
1. set the direction to forward
2. drive forward 
3. brake and hold brake button/pedal
4. vehicle is driving backward
5. after hitting the brake again, the vehicle stops

**Expected behavior**
the vehicle should stop and stand still while hitting the brake for the first time

**Screenshots**
![error](https://user-images.githubusercontent.com/47261401/63383983-369cb700-c39e-11e9-9060-37c0f7cd1049.PNG)

**Desktop (please complete the following information):**
 - OS: win10
 - FS patch version 1.4.1.0

**Additional context**
using the latest version from github

**Comment by MrMarcel5** [comment]
"Stop & go" active? or inactive?
maybe that is causing the issue

**Comment by Snickers125** [comment]
Active/Inactive doesn’t have any effect on that.

**Comment by stijnwop** [comment]
Is this only in MP?

**Comment by Snickers125** [comment]
yes, only with multiple clients

**Comment by KITT3000** [comment]
I confirm, the bug is in both directions (in MP, multiple clients), on the keyboard and the controller.

**Comment by stijnwop** [comment]
Fixed.. ;)

**Comment by Snickers125** [comment]
great!

**Comment by KITT3000** [comment]
The issue still exists.

**Comment by stijnwop** [comment]
Euhm.. what about how? Tried it in multi client with a controller.
Even @Snickers125 couldn't reproduce on the pedals

**Comment by KITT3000** [comment]
I played with friends (6 clients + host), the host had no problems, and every client had a problem all the time. At first I thought the mod version was wrong, but all files are up-to-date with the github version.

**Comment by stijnwop** [comment]
I might have forgotten to push that last fix for @Snickers125 haha

**Comment by Evilman2517** [comment]
Sadly, this issue still occurs on a dedicated server. Used the newest version and still had sometimes this behavior. It seems unrelated to the input device, as one player uses a keyboard, another one a gamepad and one uses a steeringwheel.

I'm not quite sure, but had the "feeling" it got worse after a new player joined and after some time it disappeared
